/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 14:01:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>欢迎登录</title>\r\n");
      out.write("        \r\n");
      out.write(" <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <link href=\"css/loginStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("     <div id=\"main\">\r\n");
      out.write("\t    <div id=\"header\">\r\n");
      out.write("\t    \t<div id=\"log\"></div>\r\n");
      out.write("\t    \t<div id=\"huangyingdenglu\">欢迎登录</div>\r\n");
      out.write("\t    \t<div id=\"dengluyemian\">\r\n");
      out.write("\t    \t\t<div id=\"huihua\">\r\n");
      out.write("\t    \t\t</div><label style=\"float:left;line-height:20px;font-weight:10px;\">登录页面，调查问卷</label>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t     <div id=\"content\">\r\n");
      out.write("\t\t     <div id=\"login\">\r\n");
      out.write("\t\t     \t<div style=\"width:250px;height:50px;margin-left:60px;border-bottom:1px solid #F6F6F6\">\r\n");
      out.write("\t\t     \t\t<a class=\"zi\" style=\"float:left;text-decoration:none;\">扫码登录</a>\r\n");
      out.write("\t\t     \t\t<a class=\"zi\" style=\"float:left;margin-left:50px;text-decoration:none;\">账户登录</a>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t     \t<div id=\"login-box\">\r\n");
      out.write("\t\t     \t\t<form action=\"doLogin\" method=\"post\">\r\n");
      out.write("\t\t     \t\t\t <div class=\"login-box-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2\" style=\"line-height:40px;width:40px;height:40px;background-image:url(images/pwd-icons-new.png);\" ></label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"in\" type=\"text\" name=\"username\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t placeholder=\"邮箱/用户名/已验证手机\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login-box-in\" >\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2\" style=\"line-height:40px;width:40px;height:40px;background-image:url(images/pwd-icons-new.png);\r\n");
      out.write("\t\t\t\t\t\t\t\tbackground-position:-48px 0px;\" ></label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"in\" type=\"password\" name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t placeholder=\"请输入密码\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"forgetPwd\" style=\"width:100px;height:30px;margin-left:200px;text-align:right;line-height:30px;cursor:pointer\"><a>忘记密码</a></div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"login-box-in\" style=\"border:none;background-color:red;font-size:20px;\r\n");
      out.write("\t\t    \t\tmargin-top:20px;margin-left:45px;text-align:center\" value=\"登录\"/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t     \t\t</form>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t     \t<div id=\"login-foot\">\r\n");
      out.write("\t\t     \t\t<ul id=\"login-method\">\r\n");
      out.write("\t\t     \t\t\t<li style=\"margin-top:10px;\"> <a href=\"http://www.baidu.com\">\r\n");
      out.write("\t\t     \t\t\t\t<ul style=\"list-style:none;float:left;\">\r\n");
      out.write("\t\t     \t\t\t\t\t<li style=\"width:20px;height:18px;background-image:url(images/QQ-weixin.png);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbackground-position:0px 0px;\"></li>\r\n");
      out.write("\t\t     \t\t\t\t\t<li>\r\n");
      out.write("\t\t     \t\t\t\t\t\tQQ&nbsp;&nbsp;|\r\n");
      out.write("\t\t     \t\t\t\t\t</li>\r\n");
      out.write("\t\t     \t\t\t\t</ul></a>\r\n");
      out.write("\t\t     \t\t\t</li>\r\n");
      out.write("\t\t     \t\t\t<li style=\"margin-top:10px;\"> <a href=\"http://www.baidu.com\">\r\n");
      out.write("\t\t     \t\t\t\t<ul style=\"list-style:none;float:left;\">\r\n");
      out.write("\t\t     \t\t\t\t\t<li style=\"width:20px;height:18px;background-image:url(images/QQ-weixin.png);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbackground-position:20px 0px;\"></li>\r\n");
      out.write("\t\t     \t\t\t\t\t<li>\r\n");
      out.write("\t\t     \t\t\t\t\t\t微信\r\n");
      out.write("\t\t     \t\t\t\t\t</li>\r\n");
      out.write("\t\t     \t\t\t\t</ul></a>\r\n");
      out.write("\t\t     \t\t\t</li>\r\n");
      out.write("\t\t     \t\t\t<li style=\"margin-top:10px;margin-left:100px;\"> <a href=\"showRegister\">\r\n");
      out.write("\t\t     \t\t\t\t<ul style=\"list-style:none;float:left;\">\r\n");
      out.write("\t\t     \t\t\t\t\t<li style=\"width:20px;height:18px;background-image:url(images/pwd-icons-new.png);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbackground-position:20px 100px;\"></li>\r\n");
      out.write("\t\t     \t\t\t\t\t<li>\r\n");
      out.write("\t\t     \t\t\t\t\t\t立即注册\r\n");
      out.write("\t\t     \t\t\t\t\t</li>\r\n");
      out.write("\t\t     \t\t\t\t</ul></a>\r\n");
      out.write("\t\t     \t\t\t</li>\r\n");
      out.write("\t\t     \t\t</ul>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t     \r\n");
      out.write("\t     </div>\r\n");
      out.write("\t     <div id=\"footer\">\r\n");
      out.write("\t    \t<div class=\"links\">\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">关于我们&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">联系我们&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">人才招聘&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">商家入驻&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">广告服务&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">手机京东&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">友情链接&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">销售联盟&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">京东社区&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">京东公益&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">English&nbsp;Site</a>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"Copyright\">\r\n");
      out.write("\t    \t\t Copyright&copy;2004-2016&nbsp;&nbsp;京东JD.com&nbsp;版权所有\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
