/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 14:34:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>个人注册</title>\r\n");
      out.write("    \r\n");
      out.write(" <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <link href=\"css/registerStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".qiye,.yqiye\").hover(function(){\r\n");
      out.write("\t\t$(this).removeClass(\"out\");\r\n");
      out.write("\t\t$(this).addClass(\"over\");\r\n");
      out.write("\t},\r\n");
      out.write("\tfunction(){\r\n");
      out.write("\t\t$(this).removeClass(\"over\");\r\n");
      out.write("\t\t$(this).addClass(\"out\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#img\").click(function(){\r\n");
      out.write("\t\t$(this).prop(\"src\",\"getRandom?\"+Math.random());\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"[name=qpassword]\").blur(function(){\r\n");
      out.write("\t\tvar qpwd=$(this).val();\r\n");
      out.write("\t\tvar pwd=$(\"[name=password]\").val();\r\n");
      out.write("\t\tif(qpwd!=pwd){\r\n");
      out.write("\t\t\talert(\"两次输入的密码不一致\");\r\n");
      out.write("\t\t\t$(this).val(\"\");\r\n");
      out.write("\t\t\t$(\"[name=password]\").val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"[name=yanzheng]\").blur(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"testRandom\",\r\n");
      out.write("\t\t\tdata:\"text=\"+$(\"[name=yanzheng]\").val(),\r\n");
      out.write("\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data!=\"success\"){\r\n");
      out.write("\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t$(\"[name=yanzheng]\").val(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"form\").submit(function(){\r\n");
      out.write("\t\tvar user = $(\"[name=username]\").val();\r\n");
      out.write("\t\tvar pwd = $(\"[name=password]\").val();\r\n");
      out.write("\t\tvar tel = $(\"[name=telphone]\").val();\r\n");
      out.write("\t\tvar yanzheng = $(\"[name=yanzheng]\").val();\r\n");
      out.write("\t\tvar telyanzheng = $(\"[name=telyanzheng]\").val();\r\n");
      out.write("\t\tif(user==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入用户名\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pwd==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入密码\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(tel==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入手机号\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(telyanzheng==\"\"){\r\n");
      out.write("\t\t\talert(\"请输入手机验证码\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".over{\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".out{\r\n");
      out.write("\tcursor:default;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("\t    <div id=\"header\">\r\n");
      out.write("\t    \t<div id=\"log\"></div>\r\n");
      out.write("\t    \t<div id=\"huangyingzhuce\">欢迎注册</div>\r\n");
      out.write("\t    \t<div id=\"denglu\">已有账号？&nbsp;<a href=\"login\" style=\"cursor:pointer;color:red;text-decoration:none;\">请登录</a></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"content\">\r\n");
      out.write("\t\t    <div id=\"dianji\">\r\n");
      out.write("\t\t    \t<form id=\"from\" action=\"login\" method=\"post\">\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\" style=\"margin-top:0px;\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"user\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t    \t\t\t\t\t<label class=\"col-sm-3 control-label\">用&nbsp;&nbsp;&nbsp;户&nbsp;&nbsp;&nbsp;名</label>\r\n");
      out.write("\t\t    \t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t    \t\t\t\t\t<input type=\"text\" name=\"username\" class=\"input\" placeholder=\"您的用户名和登录名\"/>\r\n");
      out.write("\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"password\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t\t    \t\t\t\t<label class=\"col-sm-3 control-label\">设&nbsp;置&nbsp;密&nbsp;码</label>\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t    \t\t\t\t<input type=\"password\" name=\"password\" class=\"input\" placeholder=\"建议至少使用两种字符组合\"/>\r\n");
      out.write("\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"qpassword\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t    \t\t\t\t<label class=\"col-sm-3 control-label\">确&nbsp;认&nbsp;密&nbsp;码</label>\r\n");
      out.write("\t\t    \t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t    \t\t\t\t<input type=\"password\" name=\"qpassword\" class=\"input\" placeholder=\"请再次输入密码\"/>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"phone\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t    \t\t\t\t<label class=\"col-sm-3 control-label\">中国&nbsp;0086</label>\r\n");
      out.write("\t\t    \t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t    \t\t\t\t<input type=\"text\" name=\"telphone\" class=\"input\" placeholder=\"建议使用常用手机\" /></div>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"yanzhengma\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t\t    \t\t\t\t<label class=\"col-sm-3 control-label\">验&nbsp;&nbsp;证&nbsp;&nbsp;码</label>\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t    \t\t\t\t<input type=\"password\" name=\"yanzheng\" class=\"input\" placeholder=\"请输入验证码\"/></div>\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<img id=\"img\" style=\"width:134px; height:50px;\" src=\"getRandom\">\r\n");
      out.write("\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div class=\"zhucekuang\">\r\n");
      out.write("\t\t    \t\t\t<div id=\"phoneyanzheng\">\r\n");
      out.write("\t\t    \t\t\t\t<div>\r\n");
      out.write("\t\t\t    \t\t\t\t<label class=\"col-sm-3 control-label\">手机验证码</label>\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t    \t\t\t\t<input type=\"text\" name=\"telyanzheng\"  class=\"input\" placeholder=\"请输入手机验证码\"/>\r\n");
      out.write("\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    \t\t\t\t<button class=\"col-sm-4\" id=\"getTelRandom\">获取验证码</button>\r\n");
      out.write("\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t\r\n");
      out.write("\t\t    \t\t\t</div>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<div style=\"width:400px;height:50px;margin-left:50px;line-height:50px;\">\r\n");
      out.write("\t\t    \t\t<input type=\"checkbox\" checked/>阅读并同意<a style=\"text-decoration:none;cursor:pointer;\">《京东用户注册协议》</a>&nbsp;\r\n");
      out.write("\t\t    \t\t<a style=\"text-decoration:none;cursor:pointer;\">《隐私政策》</a>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t    \t\t<input type=\"submit\" class=\"zhucekuang\" style=\"border:none;background-color:red;font-size:20px;\r\n");
      out.write("\t\t    \t\tmargin-top:10px;text-align:center\" value=\"立即注册\"/>\r\n");
      out.write("\t\t    \t</form>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div id=\"about\">\r\n");
      out.write("\t\t    \t<div class=\"qiye\">\r\n");
      out.write("\t\t\t    \t<div id=tubiao1></div>\r\n");
      out.write("\t\t\t    \t<div id=\"qiyeyonghu\" style=\"line-height:45px;\">企业用户注册</div>\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t    \t<div class=\"yqiye\" style=\"border-top:1px #666 solid;margin-top:20px;height:55px;\">\r\n");
      out.write("\t\t\t    \t<div id=\"tubiao2\"></div>\r\n");
      out.write("\t\t\t    \t<div id=\"yqiyeyonghu\">INTERNATIONAL<br/>CUSTOMERS</div>\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div id=\"footer\">\r\n");
      out.write("\t    \t<div class=\"links\" >\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">关于我们&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">联系我们&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">人才招聘&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">商家入驻&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">广告服务&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">手机京东&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">友情链接&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">销售联盟&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">京东社区&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">京东公益&nbsp;|</a>\r\n");
      out.write("\t\t    \t<a style=\"text-decoration:none;\">English&nbsp;Site</a>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"Copyright\">\r\n");
      out.write("\t    \t\t Copyright&copy;2004-2016&nbsp;&nbsp;京东JD.com&nbsp;版权所有\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
