/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 14:39:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.User;
import java.util.*;

public final class modifyPwd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'modifPwd.jsp' starting page</title>\r\n");
      out.write("        <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    ");
User user = (User)request.getSession().getAttribute("user");
    System.out.print(user.getUsername());
     if(user!=null){
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$().ready(function(){\r\n");
      out.write("\t$(\"[name=opassword]\").blur(function(){\r\n");
      out.write("\t\tvar oPwd = $(this).val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"compareMPwd\",\r\n");
      out.write("\t\t\tdata:\"oPwd=\"+oPwd,\r\n");
      out.write("\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data!=\"true\"){\r\n");
      out.write("\t\t\t\t\t$(\"#opasswordmes\").html(data);\r\n");
      out.write("\t\t\t\t\t$(\"[name=opassword]\").val(\"\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#opasswordmes\").html(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"[name=qpassword]\").blur(function(){\r\n");
      out.write("\t\tvar pwd = $(\"[name=qpassword]\").val();\r\n");
      out.write("\t\tvar qpwd = $(this).val();\r\n");
      out.write("\t\tif(pwd!=qpwd){\r\n");
      out.write("\t\t\talert(\"两次输入的密码不同！\");\r\n");
      out.write("\t\t\t$(this).val(\"\");\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   <div style=\"width:515px;margin:20px auto;height:430px;\">\r\n");
      out.write("  <form action=\"ModifyMpwd\" method=\"post\"  enctype=\"multipart/form-data\"  class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("  <div class=\"form-group\" >\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">请输入原密码：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"opassword\" class=\"form-control\"  placeholder=\"请输入原密码\"/></div>\r\n");
      out.write("   \t\t<div id=\"opasswordmes\" class=\"col-sm-4\" style=\"color:red;line-height:30px;\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("  \t\t<label class=\"col-sm-3 control-label\">请输入新密码：</label>\r\n");
      out.write("  \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"password\" class=\"form-control\"  placeholder=\"请输入新密码\"/></div>\r\n");
      out.write("  \t\t<div id=\"passwordmsg\" class=\"col-sm-4\" style=\"color:red;line-height:30px;\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("  \t\t<label class=\"col-sm-3 control-label\">请确认新密码：</label>\r\n");
      out.write("  \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"qpassword\" class=\"form-control\"  placeholder=\"请确认新密码\"/></div>\r\n");
      out.write("  \t\t<div id=\"qpasswordmsg\" class=\"col-sm-4\" style=\"color:red;line-height:30px;\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\"  style=\"margin-left:150px;\" >\r\n");
      out.write("  <input type=\"submit\" class=\"btn btn-primary\" value=\"保存\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
