/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-06 10:08:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.type;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.SmallType;
import entity.BigType;
import java.util.*;

public final class showType_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>显示商品类别</title>  \r\n");
      out.write("     <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t$().ready(function(){\r\n");
      out.write("    \t//双击大分类显示小分类\r\n");
      out.write("    \t\t$(\"#bType\").dblclick(function(){\r\n");
      out.write("    \t\t\tvar bId = $(this).val();\r\n");
      out.write("    \t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\ttype:\"post\",\r\n");
      out.write("    \t\t\t\turl:\"showMsType\",\r\n");
      out.write("    \t\t\t\tdata:\"bId=\"+bId,\r\n");
      out.write("    \t\t\t\tdataType:\"text\",\r\n");
      out.write("    \t\t\t\tsuccess:function(data){\r\n");
      out.write("    \t\t\t\t\tif(data==\"\"){\r\n");
      out.write("    \t\t\t\t\t$(\"#sType\").html(\"\");\r\n");
      out.write("    \t\t\t\t\t}else{\r\n");
      out.write("\t    \t\t\t\t\tvar mes = data.substring(0,data.length -1);\r\n");
      out.write("\t    \t\t\t\t\tvar str = mes.split(\";\");\r\n");
      out.write("\t    \t\t\t\t\tvar options =\"\";\r\n");
      out.write("\t    \t\t\t\t\tfor(var i = 0; i < str.length;i++){\r\n");
      out.write("\t    \t\t\t\t\t\tvar sType = str[i].split(\",\");\r\n");
      out.write("\t    \t\t\t\t\t\toptions +=\"<option value=\"+sType[0]+\">\"+sType[1]+\"</option>\";\r\n");
      out.write("\t    \t\t\t\t\t}\r\n");
      out.write("\t    \t\t\t\t\t$(\"#sType\").html(options);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\t//添加大分类\r\n");
      out.write("    \t$(\"#bButton\").click(function(){\r\n");
      out.write("    \t\tvar bType = prompt(\"请输入大分类的名称\");\r\n");
      out.write("    \t\tif(bType != null){\r\n");
      out.write("\t    \t\t$.ajax({\r\n");
      out.write("\t    \t\t\ttype:\"post\",\r\n");
      out.write("\t    \t\t\turl:\"addMbType\",\r\n");
      out.write("\t    \t\t\tdata:\"bType=\" + bType,\r\n");
      out.write("\t    \t\t\tdataType:\"text\",\r\n");
      out.write("\t    \t\t\tsuccess:function(data){\r\n");
      out.write("\t    \t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t    \t\t\t\t\twindow.location.href=\"showMType\";\r\n");
      out.write("\t    \t\t\t\t}else{\r\n");
      out.write("\t    \t\t\t\t\talert(data);\r\n");
      out.write("\t    \t\t\t\t}\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t//删除大分类\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t//修改大分类\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t//添加小分类\r\n");
      out.write("    \t$(\"#sButton\").click(function(){\r\n");
      out.write("    \t\tvar options=$(\"#bType option:selected\");//获取选中的项\r\n");
      out.write("\t\t\tvar bId = options.val();   //拿到选中项的值\r\n");
      out.write("\t\t\tvar bName = options.text();   //拿到选中项的文本\r\n");
      out.write("    \t\tvar bId = $(\"#bType\").val();\r\n");
      out.write("    \t\tvar sName = prompt(\"请输入“\"+bName+\"”要添加的小分类的名称\");\r\n");
      out.write("    \t\tif(sName != null){\r\n");
      out.write("    \t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\ttype:\"post\",\r\n");
      out.write("\t    \t\t\turl:\"addMsType\",\r\n");
      out.write("\t    \t\t\tdata:\"bId=\" + bId+\"&sName=\"+sName,\r\n");
      out.write("\t    \t\t\tdataType:\"text\",\r\n");
      out.write("\t    \t\t\tsuccess:function(data){\r\n");
      out.write("\t    \t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t    \t\t\t\t\twindow.location.href=\"showMType\";\r\n");
      out.write("\t    \t\t\t\t}else{\r\n");
      out.write("\t    \t\t\t\t\talert(data);\r\n");
      out.write("\t    \t\t\t\t}\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t//删除小分类\r\n");
      out.write("    \t\t$(\"#delsButton\").click(function(){\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tvar sOptions = $(\"#sType\").val();\r\n");
      out.write("    \t\t\tif(sOptions==null){\r\n");
      out.write("    \t\t\t\t\talert(\"请选中要删除的小分类\");\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\tvar sTId = sOptions;\r\n");
      out.write("    \t\t\t\tvar sTName = $(\"#sType option:selected\").html();\r\n");
      out.write("    \t\t\t\tvar a = confirm(\"是否要删除选中的小分类:‘\"+sTName+\"’？\");\r\n");
      out.write("    \t\t\t\tif(a==true){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("    \t\t\t\t\t\turl:\"delMsType\",\r\n");
      out.write("    \t\t\t\t\t\tdata:\"sId=\"+sTId,\r\n");
      out.write("    \t\t\t\t\t\tdataType:\"text\",\r\n");
      out.write("    \t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("    \t\t\t\t\t\t\tif(data==\"success\"){\r\n");
      out.write("    \t\t\t\t\t\t\t\talert(\"删除成功！\");\r\n");
      out.write("    \t\t\t\t\t\t\t\twindow.location.href=\"showMType\";\r\n");
      out.write("    \t\t\t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\t\t\talert(data);\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t});\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t//修改小分类\r\n");
      out.write("    \t$(\"#modisButton\").click(function(){\r\n");
      out.write("    \t\t\tvar sOptions = $(\"#sType\").val();\r\n");
      out.write("    \t\t\tif(sOptions==null){\r\n");
      out.write("    \t\t\t\t\talert(\"请选中要修改的小分类\");\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\tvar sTId = sOptions;\r\n");
      out.write("    \t\t\t\tvar sTName = $(\"#sType option:selected\").html();\r\n");
      out.write("    \t\t\t\t var nsName = prompt(\"请输入要修改的小分类的名称\");\r\n");
      out.write("    \t\t\t\tif(nsName !=null){\r\n");
      out.write("    \t\t\t\t \t\r\n");
      out.write("\t    \t\t\t\t$.ajax({\r\n");
      out.write("\t    \t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t    \t\t\t\t\t\turl:\"modifyMsType\",\r\n");
      out.write("\t    \t\t\t\t\t\tdata:\"sId=\"+sTId +\"&nsName=\"+nsName,\r\n");
      out.write("\t    \t\t\t\t\t\tdataType:\"text\",\r\n");
      out.write("\t    \t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t    \t\t\t\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t    \t\t\t\t\t\t\t\talert(\"修改成功！\");\r\n");
      out.write("\t    \t\t\t\t\t\t\t\twindow.location.href=\"showMType\";\r\n");
      out.write("\t    \t\t\t\t\t\t\t}else{\r\n");
      out.write("\t    \t\t\t\t\t\t\t\talert(data);\r\n");
      out.write("\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t    \t\t\t\t\t\t}\r\n");
      out.write("\t    \t\t\t\t});\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .centent{\r\n");
      out.write("    \tmargin-top:50px;\r\n");
      out.write("        float:left;\r\n");
      out.write("    \twidth:400px;\r\n");
      out.write("    \theight:400px;\r\n");
      out.write("    }\r\n");
      out.write("   #bType,#sType{\r\n");
      out.write("   \t\twidth:400px;\r\n");
      out.write("    \theight:400px;\r\n");
      out.write("    \tfont-size:18px;\r\n");
      out.write("   }\r\n");
      out.write("   #bButton,#sButton{\r\n");
      out.write("   \tmargin-top:10px;\r\n");
      out.write("   margin-left:50px;\r\n");
      out.write("   }\r\n");
      out.write("   #sButton{\r\n");
      out.write("   \tmargin-left:250px;\r\n");
      out.write("   }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");
 List<BigType> bType = (List<BigType>)request.getAttribute("btypelist"); 
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("    <div class=\"centent\">\r\n");
      out.write("    <select multiple id=\"bType\">\r\n");
      out.write("    ");
for(int i = 0; i < bType.size();i++){ 
      out.write("\r\n");
      out.write("    <option value=\"");
      out.print(bType.get(i).getId());
      out.write('"');
      out.write(' ');
if(i==0){out.print("selected");} 
      out.write('>');
      out.print(bType.get(i).getName() );
      out.write("</option>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"centent\" style=\"margin-left:100px;\">\r\n");
      out.write("    ");
List<SmallType> sType = bType.get(0).getSmallType(); 
      out.write("\r\n");
      out.write("    <select multiple id=\"sType\">\r\n");
      out.write("    \t");
for(int i = 0; i < sType.size();i++){ 
      out.write("\r\n");
      out.write("    \t\t<option value=\"");
      out.print(sType.get(i).getId() );
      out.write('"');
      out.write('>');
      out.print(sType.get(i).getName() );
      out.write("</option>\r\n");
      out.write("    \t");
} 
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"clear:both\">\r\n");
      out.write("     <button id=\"bButton\">添加大分类</button>\r\n");
      out.write("     <button id=\"delbButton\">删除大分类</button>\r\n");
      out.write("     <button id=\"modibButton\">修改大分类</button>\r\n");
      out.write("    <button id=\"sButton\">添加小分类</button>\r\n");
      out.write("    <button id=\"delsButton\">删除小分类</button>\r\n");
      out.write("    <button id=\"modisButton\">修改小分类</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
