/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-12 11:25:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.type;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.User;
import entity.SmallType;
import entity.BigType;
import java.util.*;

public final class type_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'shouye.jsp' starting page</title>\r\n");
      out.write("    <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/ bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<link href=\"css/typeStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t<script>\r\n");
      out.write("$().ready(function(e) {\r\n");
      out.write("    var imgs=$(\"#slide li\");\r\n");
      out.write("\tvar icons=$(\".active li\");\r\n");
      out.write("\timgs.hide();\r\n");
      out.write("\t$(\"#left,#right\").hide();\r\n");
      out.write("\timgs.eq(0).show();\r\n");
      out.write("\ticons.eq(0).addClass(\"active\");\r\n");
      out.write("\tvar i=0;\r\n");
      out.write("\tfunction change(){\r\n");
      out.write("\t\ti++;\r\n");
      out.write("\t\tif(i==imgs.length){\r\n");
      out.write("\t\t\ti=0;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tselected();\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selected(){\r\n");
      out.write("\t\timgs.hide();\r\n");
      out.write("\t\timgs.eq(i).show();\r\n");
      out.write("\t\ticons.removeClass(\"active\");\r\n");
      out.write("\t\ticons.eq(i).addClass(\"active\");\t\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#d521\").hover(function(){\r\n");
      out.write("\t\t$(\"#left,#right\").show();\r\n");
      out.write("\t\t$(\"#d521\").css(\"cursor\",\"pointer\");\r\n");
      out.write("\t\tclearInterval(timer);\r\n");
      out.write("\t},\r\n");
      out.write("\tfunction(){\r\n");
      out.write("\t\t$(\"#left,#right\").hide();\r\n");
      out.write("\t\t$(\"#d521\").css(\"cursor\",\"defualt\");\r\n");
      out.write("\t\t timer=setInterval(change,2000);\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#left\").hover(function(){\r\n");
      out.write("\t\t$(\"#left\").css(\"background\",\"#643B36\");\r\n");
      out.write("\t\t},function(){\r\n");
      out.write("\t\t$(\"#left\").css(\"background\",\"#D1DCE6\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$(\"#right\").hover(function(){\r\n");
      out.write("\t\t$(\"#right\").css(\"background\",\"#643B36\");\r\n");
      out.write("\t\t},function(){\r\n");
      out.write("\t\t$(\"#right\").css(\"background\",\"#D1DCE6\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\ticons.click(function(){\r\n");
      out.write("\t\ti=$(this).index();\r\n");
      out.write("\t\tselected();\r\n");
      out.write("\t\tclearInterval(timer);\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#left a\").click(function(){\r\n");
      out.write("\t\ti--;\r\n");
      out.write("\t\tif(i<0){\r\n");
      out.write("\t\t\ti=imgs.length-1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tselected();\r\n");
      out.write("\t\tclearInterval(timer);\t\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#right a\").click(function(){\r\n");
      out.write("\t\ti++;\r\n");
      out.write("\t\tif(i==imgs.length){\r\n");
      out.write("\t\t\ti=0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tselected();\t\r\n");
      out.write("\t\tclearInterval(timer);\r\n");
      out.write("\t});\r\n");
      out.write("\tvar timer=setInterval(change,2000);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".d411\").mouseover(function(){\r\n");
      out.write("\t\t$(\"#d51\").css(\"height\",\"800px\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#d51\").mouseover(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#d51\").css(\"height\",\"800px\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#d51\").mouseout(function(){\r\n");
      out.write("\t\t$(\"#d51\").css(\"height\",\"480px\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"[name=loginOut]\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"loginOut\",\r\n");
      out.write("\t\t\tdata:\"\",\r\n");
      out.write("\t\t\tdataType:\"\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\twindow.location.href=\"showType\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#header{\r\n");
      out.write("\t\tmargin:1px auto;\r\n");
      out.write("\t\theight:230px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.over{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tcolor:red;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.out{\r\n");
      out.write("\t\tcursor:default;\r\n");
      out.write("\t\tcolor:default;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\tiframe {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <div style=\"margin:1px auto;width:1366px;height:600px;background-color:#F6F6F6\">\r\n");
      out.write("   <div id=\"header\" class=\"row\">\r\n");
      out.write("           <div id=\"d1\">\r\n");
      out.write("    <div id=\"d11\">送至：北京&or;</div>\r\n");
      out.write("    <div id=\"d12\">\r\n");
      out.write("      <ul class=\"u1\">\r\n");
      out.write("      ");
User user = (User)request.getSession().getAttribute("user"); 
      if(user==null){
      out.write("\r\n");
      out.write("        <li style=\"width:180px\"><a target=\"_top\" href=\"showLogin\"  style=\"text-decoration:none;\">你好，请登录</a> <a href=\"showRegister\" target=\"_top\" style=\"color:#F33;text-decoration:none;\">请注册</a></li>\r\n");
      out.write("        ");
}else if(user.getType().equals("管理员")){ 
      out.write("\r\n");
      out.write("        \t<li style=\"width:250px;margin-left:100px;\">欢迎你");
      out.print(user.getUsername() );
      out.write("&nbsp;&nbsp;&nbsp;<a href=\"showManage\" target=\"_top\" style=\"text-decoration:none\">去后台管理中心</a>&nbsp;&nbsp;&nbsp;<span name=\"loginOut\" style=\"cursor:pointer;text-decoration:none;\">注销</span></li>\r\n");
      out.write("        ");
}else{ 
      out.write("\r\n");
      out.write("        \t<li id=\"we\"  style=\"width:180px;margin-left:100px;\">欢迎你");
      out.print(user.getUsername() );
      out.write("&nbsp;&nbsp;&nbsp;<span name=\"loginOut\" style=\"cursor:pointer;text-decoration:none;\">注销</span></li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        <li>我的订单</li>\r\n");
      out.write("        <li>我的京东&or;</li>\r\n");
      out.write("        <li>京东会员</li>\r\n");
      out.write("        <li>手机京东&or;</li>\r\n");
      out.write("        <li>关注京东&or;</li>\r\n");
      out.write("        <li>客户服务&or;</li>\r\n");
      out.write("        <li>网站导航&or;</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d2\"> </div>\r\n");
      out.write("  <div id=\"d3\">\r\n");
      out.write("    <div id=\"d31\"><a href=\"http://www.jd.com/\" target=\"_top\"><img src=\"images/jingdongDog.png\"/></a></div>\r\n");
      out.write("    <div id=\"d32\">\r\n");
      out.write("      <input class=\"text1\" type=\"text\" id=\"selectbooktext\" placeholder=\"莫言\" style=\"font-weight:bold\"/>\r\n");
      out.write("      <div class=\"sousuo\">搜索</div>\r\n");
      out.write("      <div id=\"message\" ></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d33\">\r\n");
      out.write("      <div class=\"shoppingCar\"></div>\r\n");
      out.write("      <div class=\"word\"><a href=\"showCart\" target=\"_top\" style=\"cursor:pointer;text-decoration:none;\">我的购物车 ></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d34\">\r\n");
      out.write("      <ul class=\"menueu1\">\r\n");
      out.write("        <li>图书钜惠</li>\r\n");
      out.write("        <li>文学奖</li>\r\n");
      out.write("        <li>非虚构</li>\r\n");
      out.write("        <li style=\"width: 60px;\">每150减50</li>\r\n");
      out.write("        <li>思维导图</li>\r\n");
      out.write("        <li>每49减15</li>\r\n");
      out.write("        <li>高考三轮</li>\r\n");
      out.write("        <li>Python</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d4\">\r\n");
      out.write("    <div id=\"d41\">\r\n");
      out.write("      <div class=\"d411\">图书分类</div>\r\n");
      out.write("      <div class=\"d412\">&or;</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d42\">\r\n");
      out.write("      <ul class=\"menueu2\">\r\n");
      out.write("        <li>首页</li>\r\n");
      out.write("        <li>预售</li>\r\n");
      out.write("        <li style=\"width:50px\">电子书</li>\r\n");
      out.write("        <li style=\"width:70px\">陪伴计划</li>\r\n");
      out.write("        <li style=\"width:70px\">特色书店</li>\r\n");
      out.write("        <li style=\"width:70px\">邮币商城</li>\r\n");
      out.write("        <li>社区</li>\r\n");
      out.write("        <li style=\"width:70px\">图书勋章</li>\r\n");
      out.write("        <li>特价</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <div id=\"d5\">\r\n");
      out.write("\t<div id=\"d51\">\r\n");
      out.write("\t");
List<BigType> bigtype = (List<BigType>)request.getAttribute("bigType");
    		for(int i=0;i<bigtype.size();i++){
    	 
      out.write("\r\n");
      out.write("    \t<ul class=\"shangpin\" data-bid=\"");
      out.print(bigtype.get(i).getId() );
      out.write("\">\r\n");
      out.write("    \t<li><a style=\"color:#fff;text-decoration:none;\" href=\"list?bId=");
      out.print(bigtype.get(i).getId() );
      out.write('"');
      out.write('>');
      out.print(bigtype.get(i).getName() );
      out.write("</a></li>\r\n");
      out.write("    \t<li >\t");
 
    		List<SmallType> smallType = bigtype.get(i).getSmallType();  
    		for(int j=0;j<smallType.size();j++){ 
      out.write("\r\n");
      out.write("    \t<a style=\"font-size:12px;color:#fff;text-decoration:none;\" href=\"list?sId=");
      out.print(smallType.get(j).getId()  );
      out.write('"');
      out.write('>');
      out.print(smallType.get(j).getName() );
      out.write("</a>&nbsp;");
} 
      out.write("</li>\r\n");
      out.write("        </ul>\t\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d52\">\r\n");
      out.write("    \t<div id=\"d521\" >\r\n");
      out.write("    \t\t<ul id=\"slide\">\r\n");
      out.write("        \t\t<li><img src=\"images/jingdong1.jpg\"/></li>\r\n");
      out.write("          \t  <li><img src=\"images/jingdong2.jpg\"/></li>\r\n");
      out.write("          \t  <li><img src=\"images/jingdong3.jpg\"/></li>\r\n");
      out.write("                <li><img src=\"images/jingdong4.jpg\"/></li>\r\n");
      out.write("                <li><img src=\"images/jingdong5.jpg\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div id=\"left\" style=\"left:0px;\"><a>&lsaquo;<a></div>\r\n");
      out.write("            <div id=\"right\" style=\"right:0px;\"><a>&rsaquo;<a></div>\r\n");
      out.write("              <div id=\"icon\">\r\n");
      out.write("    \t\t\t<ul class=\"active\">\r\n");
      out.write("    \t\t\t  <li style=\"margin-left:0px;\"></li>\r\n");
      out.write("    \t\t\t  <li></li>\r\n");
      out.write("     \t\t\t  <li></li>\r\n");
      out.write("     \t\t\t  <li></li>\r\n");
      out.write("     \t\t\t  <li></li>\r\n");
      out.write("   \t\t\t \t</ul>\r\n");
      out.write("  \t\t\t  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d522\">\r\n");
      out.write("        \t<ul id=\"abouttupian\">\r\n");
      out.write("            \t<li style=\"margin-left:0px\"><img src=\"images/tupian1.jpg\"/></li>\r\n");
      out.write("                <li><img src=\"images/tupian2.jpg\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d53\">\r\n");
      out.write("    \t<div class=\"d531\">\r\n");
      out.write("        \t<div class=\"d5311\"></div>\r\n");
      out.write("            <div class=\"d5312\">\r\n");
      out.write("            \t<div class=\"d53121\">Hi，jd_4d0c140</div>\r\n");
      out.write("                <div class=\"d53122\">\r\n");
      out.write("                \t<div class=\"denglu\">登陆</div>\r\n");
      out.write("                    <div class=\"zhuce\">注册</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d5313\">\r\n");
      out.write("            \t<div class=\"fuli\">新人福利</div>\r\n");
      out.write("                <div class=\"huiyuan\">PLUS会员</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d532\">\r\n");
      out.write("        \t<div class=\"d5321\">\r\n");
      out.write("            \t<div class=\"cuxiao\">促销</div>\r\n");
      out.write("                <div class=\"gonggao\">公告</div>\r\n");
      out.write("                <div class=\"gengduo\">更多</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d5322\">\r\n");
      out.write("            \t<ul id=\"u1\">\r\n");
      out.write("                \t<li >爆款秒杀 低至五折</li>\r\n");
      out.write("                \t<li>京东健康母亲节关爱不打折</li>\r\n");
      out.write("               \t\t<li>抢4999，爆款手机买1送1</li>\r\n");
      out.write("                    <li>母亲节，有爱就“购”了</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d533\">\r\n");
      out.write("        \t<div class=\"d5331\">\r\n");
      out.write("            \t<ul id=\"u2\">\r\n");
      out.write("                \t<li style=\"color:#C03;border-top:2px solid #E01121;margin-left:-0px;\">话费</li>\r\n");
      out.write("                    <li>机票</li>\r\n");
      out.write("                    <li>酒店</li>\r\n");
      out.write("                    <li>游戏</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d5332\">\r\n");
      out.write("            \t<ul id=\"u3\">\r\n");
      out.write("                \t<li style=\"margin-left:0px;\">话费充值</li>\r\n");
      out.write("                    <li>流量充值</li>\r\n");
      out.write("                    <li>套餐变更</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d5333\">\r\n");
      out.write("            \t<ul id=\"u4\">\r\n");
      out.write("                \t<li>号码:&nbsp;<input type=\"text\" placeholder=\"移动/联通/电信\" style=\"width:90px;height:20px; font-size:12px;color:#999\">\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li style=\"width:190px;\">面值:\r\n");
      out.write("                    <select value=\"100元\" style=\"width:55px;height:20px;\">\r\n");
      out.write("                    \t<option>10元</option>\r\n");
      out.write("                        <option>20元</option>\r\n");
      out.write("                        <option>30元</option>\r\n");
      out.write("                        <option>50元</option>\r\n");
      out.write("                        <option>100元</option>\r\n");
      out.write("                        <option>200元</option>\r\n");
      out.write("                        <option>300元</option>\r\n");
      out.write("                        <option>500元</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <span style=\"font-size:12px;color:red;\">￥98.0-￥100.0</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d5334\">快速充值</div>\r\n");
      out.write("            <div class=\"d5335\">\r\n");
      out.write("            \t<div class=\"hot\"></div>\r\n");
      out.write("                <div class=\"qianghuafei\">抢50元话费券</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"d6\">\r\n");
      out.write("\t<div id=\"d61\">\r\n");
      out.write("    \t<div class=\"jiao\"></div>\r\n");
      out.write("        <div class=\"d612\"></div>\r\n");
      out.write("        <div class=\"d613\">京东秒杀</div>\r\n");
      out.write("        <div class=\"d614\">总有你想不到的低价</div>\r\n");
      out.write("        <div class=\"d615\"></div>\r\n");
      out.write("        <div class=\"d616\">当前场次</div>\r\n");
      out.write("        <div class=\"d617\">00</div>\r\n");
      out.write("        <div class=\"d618\">:</div>\r\n");
      out.write("        <div class=\"d619\">57</div>\r\n");
      out.write("        <div class=\"d6110\">:</div>\r\n");
      out.write("        <div class=\"d6111\">47</div>\r\n");
      out.write("        <div class=\"d6112\">后结束抢购</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"d7\">\r\n");
      out.write("\t<div id=\"d71\">\r\n");
      out.write("    \t<div class=\"d711\">\r\n");
      out.write("        \t<ul id=\"u5\">\r\n");
      out.write("            \t<li>曹文轩</li>\r\n");
      out.write("                <li>DK</li>\r\n");
      out.write("                <li>超级战舰</li>\r\n");
      out.write("                <li>迪士尼</li>\r\n");
      out.write("                <li>凯迪克</li>\r\n");
      out.write("                <li>辅食</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d712\">\r\n");
      out.write("        \t<ul id=\"u6\">\r\n");
      out.write("            \t<li style=\"margin-top:0px;background-color:#9F7ADD\"></li>\r\n");
      out.write("        \t\t<li>热门读物</li>\r\n");
      out.write("            \t<li>0-2岁</li>\r\n");
      out.write("            \t<li>3-6岁</li>\r\n");
      out.write("            \t<li>7-10岁</li>\r\n");
      out.write("            \t<li>11-14岁</li>\r\n");
      out.write("            \t<li>家教育儿</li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d713\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"d72\">\r\n");
      out.write("    \t<div class=\"d721\"></div>\r\n");
      out.write("        <div class=\"d722\"></div>\r\n");
      out.write("        <div class=\"d723\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"d73\">\r\n");
      out.write("    \t<ul id=\"u7\">\r\n");
      out.write("        \t<li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/qie.jpg);\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">海豚科学馆：动物妙想国（套装 全8册）</div>\r\n");
      out.write("                <div class=\"jiage\">￥90.00&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥144.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/xiaohongdou.jpg);\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">小红豆系列（套装1-3卷）</div>\r\n");
      out.write("                <div class=\"jiage\">￥33.00&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥48.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/xiaosongshu.jpg);\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">真正的蒙氏教育在家庭 蒙台梭利家庭教育解决方案（套装共4</div>\r\n");
      out.write("                <div class=\"jiage\">￥144.00&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥192.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/xiaoxuesheng.jpg);\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">DK小学生百科全书 微观世界（精装版）（全彩）</div>\r\n");
      out.write("                <div class=\"jiage\">￥98.80&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥158.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/xiaogou.jpg);\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">丽声妙想英文绘本 牛津阅读树 第一级至第四级套装(套装共4册 </div>\r\n");
      out.write("                <div class=\"jiage\">￥133.30&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥182.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<div class=\"tushutupian\" style=\"background-image:url(images/wenxuan.jpg)\"></div>\r\n");
      out.write("                <div class=\"tushumiaoshu\">正版包邮 漫步到宇宙尽头 李然 继时间简史、人类简史后，媲美</div>\r\n");
      out.write("                <div class=\"jiage\">￥33.00&nbsp;&nbsp;&nbsp;<span style=\"color:#CCC;font-size:14px;text-decoration:line-through\">￥48.00</span></div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div id=\"footer\" class=\"row\">\r\n");
      out.write("           <iframe src=\"footer\" scrolling=\"no\" frameborder=\"0\" \r\n");
      out.write("\t\t\tname=\"footer\" class=\"col-sm-12\"></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
