/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-06 10:08:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import entity.*;

public final class modifyProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>修改商品信息</title>\r\n");
      out.write("   <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
List<BigType> allType = (List<BigType>)request.getAttribute("allType");
	List<SmallType> smallType = allType.get(0).getSmallType();
	 Product product = (Product)request.getAttribute("product");
 
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \t$().ready(function(){\r\n");
      out.write(" \t\tvar options = Array();\r\n");
      out.write(" \t\t");
for(int i = 0; i < allType.size();i++){
 			for(int j = 0; j <allType.get(i).getSmallType().size(); j++){
 			SmallType smallType1 = allType.get(i).getSmallType().get(j);
      out.write("\r\n");
      out.write(" \t\t\toptions[");
      out.print(allType.get(i).getId());
      out.write("] += \"<option value='");
      out.print(smallType1.getId());
      out.write('\'');
      out.write('>');
      out.print(smallType1.getName());
      out.write("</option>\"; \r\n");
      out.write(" \t\t\t");
}
 		}
      out.write("\r\n");
      out.write(" \t\t$(\"[name=bId]\").change(function(){\r\n");
      out.write(" \t\t\tvar bId = $(this).val();\r\n");
      out.write(" \t\t\t$(\"[name='smallType.id']\").html(options[bId]);\r\n");
      out.write(" \t\t});\r\n");
      out.write(" \t\t$(\"[name=content]\").val(\"");
      out.print(product.getContent());
      out.write("\");\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t$(\"[name=img]\").click(function(){\r\n");
      out.write(" \t\t\tvar a = confirm(\"是否更改图片？\");\r\n");
      out.write(" \t\t\tif(a == true){\r\n");
      out.write(" \t\t\t\t$(\"#imgfile\").css(\"display\",\"inline\");\r\n");
      out.write(" \t\t\t}else{\r\n");
      out.write(" \t\t\t\t$(\"#imgfile\").css(\"display\",\"none\");\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t});\r\n");
      out.write(" \t});\r\n");
      out.write(" \t\r\n");
      out.write(" </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");
 List<Publishing> publist =  (List<Publishing>)request.getAttribute("publist"); 
 
      out.write("\r\n");
      out.write("   <div style=\"width:500px;margin:20px auto;height:430px;\">\r\n");
      out.write("  <form action=\"ModifyMProduct\" method=\"post\"  enctype=\"multipart/form-data\"  class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("  <input type=\"hidden\" name=\"id\" value=\"");
      out.print(product.getId());
      out.write("\">\r\n");
      out.write("  <div class=\"form-group\" >\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">商品名称：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"name\" class=\"form-control\" value=\"");
      out.print(product.getName() );
      out.write("\"  placeholder=\"请输入名字\"/></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("  \t\t<label class=\"col-sm-3 control-label\">单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;价：</label>\r\n");
      out.write("  \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"price\" class=\"form-control\" value=\"");
      out.print(product.getPrice() );
      out.write("\" placeholder=\"请输入单价\"/></div>\r\n");
      out.write("  \t\t<div id=\"msg\" class=\"col-sm-4\" style=\"color:red;line-height:30px;\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\" >\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">库存数量：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-5\"><input type=\"text\" name=\"num\" class=\"form-control\" value=\"");
      out.print(product.getNum() );
      out.write("\"  placeholder=\"请输入库存数量\"/></div>\r\n");
      out.write("  </div>\r\n");
      out.write(" <div class=\"form-group\">\r\n");
      out.write("      ");
String picture="default.jpg";
  			if(product.getPicture()!=null){
  				if(product.getPicture()!=""){
  					picture=product.getPicture();
  				}
  			} 
      out.write("\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">照&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;片：</label>\r\n");
      out.write("   \t\t <div class=\"col-sm-1\"><img name=\"img\" style=\"width: 30px;height:30px;\" src=\"managePicture/");
      out.print(picture );
      out.write("\"/></div>\r\n");
      out.write("   \t\t<div id=\"imgfile\" style=\"display:none\" class=\"col-sm-5\"><input type=\"file\" name=\"mypicture\"  class=\"form-control\"/></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">商品简介：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-5\"><textarea name=\"content\" %>\" class=\"form-control\"></textarea></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;者：</label>\r\n");
      out.write("    \t<div class=\"col-sm-5\"><input type=\"text\" name=\"author\" value=\"");
      out.print(product.getAuthor() );
      out.write("\" class=\"form-control\"/></div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">商品分类：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<select name=\"bId\" class=\"form-control\">\r\n");
      out.write("\t\t\t");
for(int i = 0;i < allType.size(); i++){ 
      out.write("\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(allType.get(i).getId());
      out.write('"');
      out.write(' ');
if(allType.get(i).getId()==product.getSmallType().getBigType().getId()){ out.print("selected");} 
      out.write('>');
      out.print(allType.get(i).getName() );
      out.write("</option>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<select name=\"smallType.id\" class=\"form-control\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(product.getSmallType().getId() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(product.getSmallType().getName() );
      out.write("</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("   \t\t<label class=\"col-sm-3 control-label\">出&nbsp;&nbsp;版&nbsp;&nbsp;社：</label>\r\n");
      out.write("   \t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t<select name=\"publishing.id\" class=\"form-control sId\">\r\n");
      out.write("\t\t\t<option value=\"-1\">请选择出版社</option>\r\n");
      out.write("\t\t\t");
for(int i = 0 ;i <  publist.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(publist.get(i).getId() );
      out.write('"');
      out.write(' ');
if(product.getPublishing().getId() == publist.get(i).getId()){out.print("selected");} 
      out.write('>');
      out.print(publist.get(i).getName() );
      out.write("</option>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\"  style=\"margin-left:150px;\" >\r\n");
      out.write("  <input type=\"submit\" class=\"btn btn-primary\" value=\"保存\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
