/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 14:38:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.Product;
import java.util.*;

public final class showProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>显示商品</title>\r\n");
      out.write("  <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $().ready(function(){\r\n");
      out.write("    \t$(\"[name=delete]\").click(function(){\r\n");
      out.write("    \t\tvar proId = $(this).parent().data(\"proid\");\r\n");
      out.write("    \t\tvar a = confirm(\"请确定要删除学生?\");\r\n");
      out.write("    \t\tif(a==true){\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\ttype:\"post\",\r\n");
      out.write("    \t\t\turl:\"deleteMProduct\",\r\n");
      out.write("    \t\t\tdata:\"proId=\"+proId,\r\n");
      out.write("    \t\t\tdataType:\"text\",\r\n");
      out.write("    \t\t\tsuccess:function(data){\r\n");
      out.write("    \t\t\t\tif(data==\"success\"){\r\n");
      out.write("    \t\t\t\t\talert(\"删除成功\");\r\n");
      out.write("    \t\t\t\t\twindow.location.href=\"showMProduct\";\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\talert(data);\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t$(\"[name=modify]\").click(function(){\r\n");
      out.write("    \t\tvar proId = $(this).parent().data(\"proid\");\r\n");
      out.write("    \t\twindow.location.href=\"showModifyMProduct?proId=\"+proId;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t});\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write(" \r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .picture{\r\n");
      out.write("    \twidth:30px;\r\n");
      out.write("    \theight:30px;\r\n");
      out.write("    }\r\n");
      out.write("    #search{\r\n");
      out.write("    \twidth:1025px;\r\n");
      out.write("    \theight:50px;\r\n");
      out.write("    }\r\n");
      out.write("    table tr td:nth-child(3){\r\n");
      out.write("    width:300px;\r\n");
      out.write("    }\r\n");
      out.write("    table tr td:nth-child(2){\r\n");
      out.write("    width:100px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");
List<Product> books = (List<Product>)request.getAttribute("booklist");
  int maxPage = (Integer)request.getAttribute("maxPage");
  int ye = (Integer)request.getAttribute("page");
  Product condition = (Product)request.getAttribute("condition");
  
  
      out.write("\r\n");
      out.write("  <div id=\"products\">\r\n");
      out.write("  <div id=\"search\" >\r\n");
      out.write("  <form action=\"showMProduct\" method=\"post\">\r\n");
      out.write("\t<div style=\"width:280px;float:left;margin-top:10px;\">\r\n");
      out.write("\t\t<label class=\"col-sm-4 control-label\" style=\"line-height:30px;\">商品名称:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(condition.getName() );
      out.write("\" placeholder=\"请输入商品名称\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:280px;float:left;margin-top:10px;\">\r\n");
      out.write("\t\t<label class=\"col-sm-4 control-label\" style=\"line-height:30px;\">商品种类:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"smallType.name\" class=\"form-control\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(condition.getSmallType().getName() );
      out.write("\" placeholder=\"请输入商品种类\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:280px;float:left;margin-top:10px;\">\r\n");
      out.write("\t\t<label class=\"col-sm-4 control-label\" style=\"line-height:30px;\">商品单价:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"price\" class=\"form-control\" ");
if(condition.getPrice()==-1.00){ 
      out.write("\r\n");
      out.write("\t\t\t\tvalue=\"\"");
}else{ 
      out.write("value=\"");
      out.print(condition.getPrice());
      out.write('"');
} 
      out.write(" placeholder=\"请输入商品单价\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t <button type=\"submit\" id=\"select\" class=\"btn btn-primary\" style=\"margin-top:10px;margin-left:10px;\">查询</button>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  <table class=\"table table-striped\">\r\n");
      out.write("  \t<tr >\r\n");
      out.write("  \t\t<th>商品图片</th>\r\n");
      out.write("  \t\t<th>商品名称</th>\r\n");
      out.write("  \t\t<th>商品详情</th>\r\n");
      out.write("  \t\t<th>商品单价</th>\r\n");
      out.write("  \t\t<th>商品数量</th>\r\n");
      out.write("  \t\t<th>商品种类</th>\r\n");
      out.write("  \t\t<th>作者</th>\r\n");
      out.write("  \t\t<th>出版社</th>\r\n");
      out.write("  \t\t<th>操作</th>\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  \t");
for(int i = 0; i < books.size();i++){ 
      out.write("\r\n");
      out.write("  \t\t<tr data-proid=\"");
      out.print(books.get(i).getId());
      out.write("\">\r\n");
      out.write("  \t\t\t");
String picture="default.jpg";
  			if(books.get(i).getPicture()!=null){
  				if(books.get(i).getPicture()!=""){
  					picture=books.get(i).getPicture();
  				}
  			} 
      out.write("\r\n");
      out.write("  \t\t\t<td><img class=\"picture\" src=\"managePicture/");
      out.print(picture );
      out.write("\"/></td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getName() );
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getContent() );
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getPrice() );
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getNum() );
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getSmallType().getName() );
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getAuthor());
      out.write("</td>\r\n");
      out.write("  \t\t\t<td>");
      out.print(books.get(i).getPublishing().getName());
      out.write("</td>\r\n");
      out.write("  \t\t\t<td data-proid=\"");
      out.print(books.get(i).getId() );
      out.write("\"><button name=\"modify\">修改</button><button name=\"delete\" style=\"margin-left:5px\">删除</button></td>\r\n");
      out.write("  \t\t</tr>\r\n");
      out.write("  \t");
} 
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("  <ul class=\"pagination\" style=\"margin-left:400px;\">\r\n");
      out.write("  ");
	int begin = ((ye - 1) / 5) * 5 + 1;
					int end = 0;
					int cha = maxPage - begin;
					if (cha >= 5) {
						end = begin + 4;
					} else {
						end = begin + cha;
					} 
      out.write("\r\n");
      out.write("\t<li ");
if(ye <= 1 ){ 
      out.write("class=\"disabled\"");
} 
      out.write("><a href=\"showMProduct?page=");
      out.print(ye-1 );
      out.write("&name=");
      out.print(condition.getName() );
      out.write("&smallType.name=");
      out.print(condition.getSmallType().getName() );
      out.write("&price=");
      out.print(condition.getPrice());
      out.write("\">&laquo;</a></li>\r\n");
      out.write("\t");
for(int i = begin ;i <= maxPage;i++ ) {
      out.write("\r\n");
      out.write("\t<li ");
if(ye == i ){ 
      out.write("class=\"active\"");
} 
      out.write("><a href=\"showMProduct?page=");
      out.print(i);
      out.write("&name=&smallType.name=&price=\">");
      out.print(i );
      out.write("</a></li>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<li ");
if(ye >=maxPage ){ 
      out.write("class=\"disabled\"");
} 
      out.write("><a href=\"showMProduct?page=");
      out.print(ye+1 );
      out.write("&name=");
      out.print(condition.getName() );
      out.write("&smallType.name=");
      out.print(condition.getSmallType().getName() );
      out.write("&price=");
      out.print(condition.getPrice());
      out.write("\">&raquo;</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("   </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
