/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-12 11:25:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.Product;
import java.util.*;

public final class booklb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'productliebiao.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<link href=\"css/bookLieBiaoStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t#header{\r\n");
      out.write("\t\tmargin:1px auto;\r\n");
      out.write("\t\theight:230px;\r\n");
      out.write("\t}\r\n");
      out.write("\tiframe {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$().ready(function(e) {\r\n");
      out.write("\t$(\".d51111,.d51113\").hover(function(){\r\n");
      out.write("\t\t$(this).css(\"cursor\",\"pointer\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(this).css(\"cursor\",\"default\");\r\n");
      out.write("\t\t});\r\n");
      out.write("    $(\".d51111,.d51113\").click(function(){\r\n");
      out.write("\t\twindow.location.href=\"showBook?proId=\"+$(this).parent().data(\"proid\");\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write("  </head> \r\n");
      out.write("  <body>\r\n");
      out.write("    ");

    	List<Product> booklist= (List<Product>)request.getAttribute("booklist");
    
      out.write("\r\n");
      out.write("   <div style=\"margin:1px auto;width:1366px;height:600px;background-color:#F6F6F6\">\r\n");
      out.write("   <div id=\"header\" class=\"row\">\r\n");
      out.write("           <iframe src=\"header\" scrolling=\"no\" frameborder=\"0\" \r\n");
      out.write("\t\t\tname=\"header\" class=\"col-sm-12\"></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("\t <div id=\"d5\">\r\n");
      out.write("    <div id=\"d51\">\r\n");
      out.write("      <div class=\"d511\">\r\n");
      out.write("      ");
 for(int i = 0; i < booklist.size();i++){
      out.write("\r\n");
      out.write("        <div class=\"d5111\" data-proid=\"");
      out.print(booklist.get(i).getId());
      out.write("\">\r\n");
      out.write("        ");
String picture ="default.jpg";
        if(booklist.get(i).getPicture() != null){
        	if(booklist.get(i).getPicture() !=""){
        		picture = booklist.get(i).getPicture(); 
        	}
        } 
      out.write("\r\n");
      out.write("          <div class=\"d51111\"><img style=\"width:200px;height:200px;\" src=\"images/");
      out.print(picture );
      out.write("\"/></div>\r\n");
      out.write("          <div class=\"d51112\" >￥");
      out.print(booklist.get(i).getPrice() );
      out.write("</div>\r\n");
      out.write("          <div class=\"d51113\" >");
      out.print(booklist.get(i).getName() );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d6\">\r\n");
      out.write("    <div id=\"d61\">\r\n");
      out.write("      <div class=\"d611\">\r\n");
      out.write("        <ul class=\"u1\" >\r\n");
      out.write("          <li style=\"width:50px;margin-left:-30px;\"> 上一页 </li>\r\n");
      out.write("          <li>1</li>\r\n");
      out.write("          <li>2</li>\r\n");
      out.write("          <li>3</li>\r\n");
      out.write("          <li>4</li>\r\n");
      out.write("          <li>5</li>\r\n");
      out.write("          <li>6</li>\r\n");
      out.write("          <li>7</li>\r\n");
      out.write("          <li>...</li>\r\n");
      out.write("          <li style=\"width:50px;\">下一页></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"d612\">\r\n");
      out.write("        <div style=\"float:left;width:70px;height:40px;\">共83页&nbsp;第</div>\r\n");
      out.write("        <div style=\"float:left;\">\r\n");
      out.write("          <input type=\"text\" value=\"1\" style=\"width:35px;height:35px;\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"float:left;width:5px;height:40px;margin-left:3px;\">页</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"d613\">确定</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div id=\"footer\" class=\"row\">\r\n");
      out.write("           <iframe src=\"footer\" scrolling=\"no\" frameborder=\"0\" \r\n");
      out.write("\t\t\tname=\"footer\" class=\"col-sm-12\"></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
