/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-16 12:19:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.supplier;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.SupplierOrder;
import java.util.List;

public final class showSupplierOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   <script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$().ready(function(){\r\n");
      out.write("\t\t$(\"[name=modify]\").click(function(){\r\n");
      out.write("\t\t\tvar userid = $(this).parent().data(\"userid\");\r\n");
      out.write("\t\t\twindow.location.href=\"modifySupplierOrder?id=\"+userid;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"[name=delete]\").click(function(){\r\n");
      out.write("\t\t\tvar userid = $(this).parent().data(\"userid\");\r\n");
      out.write("    \t\tvar a = confirm(\"请确定要删除该供应商?删除操作不可还原!\");\r\n");
      out.write("    \t\tif(a==true){\r\n");
      out.write("     \t\t$.ajax({\r\n");
      out.write("    \t\t\ttype:\"post\",\r\n");
      out.write("    \t\t\turl:\"doSupplierOrderDeleteById\",\r\n");
      out.write("    \t\t\tdata:\"id=\"+userid,\r\n");
      out.write("    \t\t\tdataType:\"text\",\r\n");
      out.write("    \t\t\tsuccess:function(data){\r\n");
      out.write("    \t\t\t\tconsole.log(data);\r\n");
      out.write("    \t\t\t\tif(\"200\"==data){\r\n");
      out.write("    \t\t\t\t\talert(\"删除成功!\");\r\n");
      out.write("    \t\t\t\t\twindow.location.href=\"showMSupplierOrder\";\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\talert(\"删除失败!\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t        error: function (XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("                    alert(XMLHttpRequest.status);\r\n");
      out.write("                    alert(XMLHttpRequest.readyState);\r\n");
      out.write("                    alert(textStatus);\r\n");
      out.write("            }\r\n");
      out.write("    \t\t}); \r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("    });\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");
  
  List<SupplierOrder> supplier = (List<SupplierOrder>)request.getAttribute("supplierlist");
  SupplierOrder supplierDTO=(SupplierOrder)request.getAttribute("supplier");
  if(supplierDTO==null){
	  supplierDTO=new SupplierOrder();
	  supplierDTO.setSupplierName("");
	  supplierDTO.setProName("");
  }else{
	  if(supplierDTO.getSupplierName()==null){
		  supplierDTO.setSupplierName("");
	  }
	  
	  if(supplierDTO.getProName()==null){
		  supplierDTO.setProName("");
	  }
  }
  
      out.write("\r\n");
      out.write("    <form action=\"showMSupplierOrder\" method=\"post\">\r\n");
      out.write("\t<div style=\"width:320px;float:left;margin-top:10px;\">\r\n");
      out.write("\t\t<label class=\"col-sm-4 control-label\" style=\"line-height:30px;\">供应商名称:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"supplierName\" class=\"form-control\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(supplierDTO.getSupplierName() );
      out.write("\" placeholder=\"请输入供应商名称\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:280px;float:left;margin-top:10px;\">\r\n");
      out.write("\t\t<label class=\"col-sm-4 control-label\" style=\"line-height:30px;\">产品名称:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"proName\" class=\"form-control\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(supplierDTO.getProName() );
      out.write("\" placeholder=\"请输入产品名称\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t <button type=\"submit\" id=\"select\" class=\"btn btn-primary\" style=\"margin-top:10px;margin-left:10px;\">查询</button>\r\n");
      out.write("  </form>\r\n");
      out.write("    <table class=\"table table-condensed table-bordered\">\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<th>供应商编号</th>\r\n");
      out.write("    \t\t<th>供应商名称</th>\r\n");
      out.write("    \t\t<th>供应商类型</th>\r\n");
      out.write("    \t\t<th>产品名称</th>\r\n");
      out.write("    \t\t<th>单价</th>\r\n");
      out.write("    \t\t<th>数量</th>\r\n");
      out.write("    \t\t<th>备注</th>\r\n");
      out.write("    \t\t<th style=\"width:150px;\">操作</th>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t");
for(int i = 0; i < supplier.size();i++){ 
      out.write("\r\n");
      out.write("    \t\t<tr data-userid=\"");
      out.print(supplier.get(i).getId());
      out.write("\">\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getSupplierCode() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getSupplierName() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getSupplierType() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getProName() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getProPrice() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getCount() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td>");
      out.print(supplier.get(i).getNote() );
      out.write("</td>\r\n");
      out.write("    \t\t\t<td data-userid=\"");
      out.print(supplier.get(i).getId() );
      out.write("\"><button class=\"btn btn-default\" name=\"modify\">修改</button><button name=\"delete\" class=\"btn btn-default\" style=\"margin-left:5px\">删除</button></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t");
} 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
