/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-05 14:00:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.User;
import java.util.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'header.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"css/headerStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".text1\").keyup(function(){\r\n");
      out.write("\tif($(\".text1\").val()!=\"\"){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\ttype:\"post\",\r\n");
      out.write("\t url:\"reci\",\r\n");
      out.write("\t data:\"text=\"+$(\".text1\").val(),\r\n");
      out.write("\t dataType:\"text\",\r\n");
      out.write("\t success:function(data){\r\n");
      out.write("\t \tvar data1 = data.substring(0,data.length-1);\r\n");
      out.write("\t \tvar strs = data1.split(\",\");\r\n");
      out.write("\t \tvar mes=\"\";\r\n");
      out.write("\t \tfor(var i = 0;i < strs.length; i++){\r\n");
      out.write("\t \t\tmes=strs[i]+\"<br/>\";\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \t$(\"#message\").show();\r\n");
      out.write("\t \t$(\"#message\").html(mes);\r\n");
      out.write("\t }\r\n");
      out.write("\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t$(\"#message\").hide();}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t$(\"[name=loginOut]\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"loginOut\",\r\n");
      out.write("\t\t\tdata:\"\",\r\n");
      out.write("\t\t\tdataType:\"\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\twindow.location.href=\"header\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#message{\r\n");
      out.write("\twidth: 454px;\r\n");
      out.write("\tborder:1px black solid;\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\tbachground-color:#fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"d1\">\r\n");
      out.write("    <div id=\"d11\">送至：北京&or;</div>\r\n");
      out.write("    <div id=\"d12\">\r\n");
      out.write("      <ul class=\"u1\">\r\n");
      out.write("      ");
User user = (User)request.getSession().getAttribute("user"); 
      if(user==null){
      out.write("\r\n");
      out.write("        <li style=\"width:180px\"><a target=\"_top\" href=\"showLogin\"  style=\"text-decoration:none;\">你好，请登录</a> <a href=\"showRegister\" target=\"_top\" style=\"color:#F33;text-decoration:none;\">请注册</a></li>\r\n");
      out.write("        ");
}else if(user.getType().equals("管理员")){ 
      out.write("\r\n");
      out.write("        \t<li style=\"width:250px;margin-left:100px;\">欢迎你");
      out.print(user.getUsername() );
      out.write("&nbsp;&nbsp;&nbsp;<a href=\"showManage\" target=\"_top\" style=\"text-decoration:none\">去后台管理中心</a>&nbsp;&nbsp;&nbsp;<span name=\"loginOut\" style=\"cursor:pointer;text-decoration:none;\">注销</span></li>\r\n");
      out.write("        ");
}else{ 
      out.write("\r\n");
      out.write("        \t<li id=\"we\"  style=\"width:180px;margin-left:100px;\">欢迎你");
      out.print(user.getUsername() );
      out.write("&nbsp;&nbsp;&nbsp;<span name=\"loginOut\" style=\"cursor:pointer;text-decoration:none;\">注销</span></li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        <li><a style=\"text-decoration:none;\" target=\"_top\" href=\"showOrder\">我的订单</a></li>\r\n");
      out.write("        <li>我的京东&or;</li>\r\n");
      out.write("        <li>京东会员</li>\r\n");
      out.write("        <li>手机京东&or;</li>\r\n");
      out.write("        <li>关注京东&or;</li>\r\n");
      out.write("        <li>客户服务&or;</li>\r\n");
      out.write("        <li>网站导航&or;</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d2\"> </div>\r\n");
      out.write("  <div id=\"d3\">\r\n");
      out.write("    <div id=\"d31\"><a href=\"http://www.jd.com/\" target=\"_top\"><img src=\"images/jingdongDog.png\"/></a></div>\r\n");
      out.write("    <div id=\"d32\">\r\n");
      out.write("      <input class=\"text1\" type=\"text\" id=\"selectbooktext\" placeholder=\"莫言\" style=\"font-weight:bold\"/>\r\n");
      out.write("      <div class=\"sousuo\">搜索</div>\r\n");
      out.write("      <div id=\"message\" ></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d33\">\r\n");
      out.write("      <div class=\"shoppingCar\"></div>\r\n");
      out.write("      <div class=\"word\"><a href=\"showCart\" target=\"_top\" style=\"cursor:pointer;text-decoration:none;\">我的购物车 ></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d34\">\r\n");
      out.write("      <ul class=\"menueu1\">\r\n");
      out.write("        <li>图书钜惠</li>\r\n");
      out.write("        <li>文学奖</li>\r\n");
      out.write("        <li>非虚构</li>\r\n");
      out.write("        <li style=\"width: 60px;\">每150减50</li>\r\n");
      out.write("        <li>思维导图</li>\r\n");
      out.write("        <li>每49减15</li>\r\n");
      out.write("        <li>高考三轮</li>\r\n");
      out.write("        <li>Python</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d4\">\r\n");
      out.write("    <div id=\"d41\">\r\n");
      out.write("      <div class=\"d411\">全部商品分类</div>\r\n");
      out.write("      <div class=\"d412\">&or;</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"d42\">\r\n");
      out.write("      <ul class=\"menueu2\">\r\n");
      out.write("        <li>首页</li>\r\n");
      out.write("        <li>服装城</li>\r\n");
      out.write("        <li>美妆馆</li>\r\n");
      out.write("        <li>京东超市</li>\r\n");
      out.write("        <li>生鲜</li>\r\n");
      out.write("        <li>全球购</li>\r\n");
      out.write("        <li>闪购</li>\r\n");
      out.write("        <li>拍卖</li>\r\n");
      out.write("        <li>金融</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
