/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2018-05-06 11:18:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.User;
import entity.Cart;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>购物车</title>\r\n");
      out.write("    \r\n");
      out.write("<script src=\"bootstrap/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <link href=\"css/cartStyle.css\" type = \"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script>\r\n");
      out.write("$().ready(function(e) {\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".quanxuan\").click(function(){\r\n");
      out.write("\t\tif($(this).prop(\"checked\")==false){\r\n");
      out.write("\t\t\t\t$(\".xuanzhong\").prop(\"checked\",false);\r\n");
      out.write("\t\t}else if($(this).prop(\"checked\")==true){\r\n");
      out.write("\t\t\t\t$(\".xuanzhong\").prop(\"checked\",true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tcalAllPrice();\r\n");
      out.write("\t\tcalSelected();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".xuanzhong\").click(function(){\r\n");
      out.write("\t\tif($(this).prop(\"checked\")==false){\r\n");
      out.write("\t\t\t$(\".quanxuan\").prop(\"checked\",false);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar flag = true;\r\n");
      out.write("\t\t\t$(\".xuanzhong\").each(function(index,element){\r\n");
      out.write("\t\t\t\tif($(element).prop(\"checked\")==false){\r\n");
      out.write("\t\t\t\t\t$(\".quanxuan\").prop(\"checked\",false);\r\n");
      out.write("\t\t\t\t\tflag=false;\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tif(flag){\r\n");
      out.write("\t\t\t\t$(\".quanxuan\").prop(\"checked\",true);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".quanxuan\").prop(\"checked\",false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tcalAllPrice();\r\n");
      out.write("\t\tcalSelected();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".delete\").click(function(){\r\n");
      out.write("\t\tvar proId = $(this).parent().parent().parent().data(\"proid\");\r\n");
      out.write("\t\twindow.location.href=\"deleteFromCart?proId=\"+proId;\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".delete\").hover(\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(this).css(\"cursor\",\"pointer\");\r\n");
      out.write("\t\t\t$(this).css(\"color\",\"red\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(this).css(\"cursor\",\"default\");\r\n");
      out.write("\t\t\t$(this).css(\"color\",\"#9B9B9B\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*数量增加  */\r\n");
      out.write("\t$(\".d51613\").click(function(){\r\n");
      out.write("\t\tvar num = $(this).parent().children(\".d51612\").children().val();\r\n");
      out.write("\t\tnum++;\r\n");
      out.write("\t\t$(this).parent().children(\".d51612\").children().val(num);\r\n");
      out.write("\t\tvar price = $(this).parent().parent().parent().children(\".d515\").children().html();\r\n");
      out.write("\t\tvar count = num * price;\r\n");
      out.write("\t\t$(this).parent().parent().next().children(\"a\").html(count.toFixed(\"2\"));\r\n");
      out.write("\t\tvar proId=$(this).parent().parent().parent().data(\"proid\");\r\n");
      out.write("\t\tmodifyNumAndCount(num,count.toFixed(\"2\")*1,proId);\r\n");
      out.write("\t\tcalAllPrice();\r\n");
      out.write("\t\tcalSelected();\r\n");
      out.write("\t});\r\n");
      out.write("\t/*数量减少  */\r\n");
      out.write("\t$(\".d51611\").click(function(){\r\n");
      out.write("\t\tvar num = $(this).parent().children(\".d51612\").children().val();\r\n");
      out.write("\t\tnum--;\r\n");
      out.write("\t\tif(num<1){\r\n");
      out.write("\t\t\tnum=1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(this).parent().children(\".d51612\").children().val(num);\r\n");
      out.write("\t\tvar price = $(this).parent().parent().parent().children(\".d515\").children().html();\r\n");
      out.write("\t\t var count = num * price;\r\n");
      out.write("\t\t$(this).parent().parent().next().children(\"a\").html(count.toFixed(\"2\")); \r\n");
      out.write("\t\tvar proId=$(this).parent().parent().parent().data(\"proid\");\r\n");
      out.write("\t\tmodifyNumAndCount(num,count.toFixed(\"2\")*1,proId);\r\n");
      out.write("\t\tcalAllPrice();\r\n");
      out.write("\t\tcalSelected();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".d51611,.d51613\").hover(\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(this).css(\"cursor\",\"pointer\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(this).css(\"cursor\",\"default\");\r\n");
      out.write("\t});\r\n");
      out.write("\t/*计算总价  */\r\n");
      out.write("\tfunction calAllPrice(){\r\n");
      out.write("\t\tvar zongjia = 0;\r\n");
      out.write("\t\t$(\".xuanzhong\").each(function(index,element){\r\n");
      out.write("\t\tvar count = $(this).parent().parent().children(\".d517\").children().html();\r\n");
      out.write("\t\t\tif($(element).prop(\"checked\")==true){\r\n");
      out.write("\t\t\t\tzongjia += count*1;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".zongjia\").html(zongjia.toFixed(\"2\"));\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t/*计算选中商品  */\r\n");
      out.write("\tfunction calSelected(){\r\n");
      out.write("\t\tvar allSelect = 0;\r\n");
      out.write("\t\t$(\".xuanzhong\").each(function(index,element){\r\n");
      out.write("\t\t\t if($(element).prop(\"checked\")==true){\r\n");
      out.write("\t\t\t var select = $(this).parent().parent().children(\".d516\").children().children(\".d51612\").children().val();\r\n");
      out.write("\t\t\t\tallSelect += select*1 ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".selected\").html(allSelect); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t/*使用ajax更新num和count  */\r\n");
      out.write("\tfunction modifyNumAndCount(num,count,proId){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"modifyCart\",\r\n");
      out.write("\t\t\tdata:\"num=\"+num+\"&proId=\"+proId,\r\n");
      out.write("\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\tsuccess:function(){\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\r\n");
      out.write("\t$(\"#d21\").click(function(){\r\n");
      out.write("\t\twindow.location.href=\"showMain\";\r\n");
      out.write("\t});\r\n");
      out.write("\t $(\"#d65\").click(function(){\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\t$(\".xuanzhong\").each(function(index,element){\r\n");
      out.write("\t\t\tif($(element).prop(\"checked\") == true){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tif(flag ==false){\r\n");
      out.write("\t\t\talert(\"请至少选中一件商品！\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t$(\".xuanzhong\").each(function(index,element){\r\n");
      out.write("\t\t\t\tif($(element).prop(\"checked\") == true){\r\n");
      out.write("\t\t\t\t\tvar proId = $(this).parent().parent().data(\"proid\");\r\n");
      out.write("\t\t\t\t\tstr +=proId + \",\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\twindow.location.href=\"showAccount?proIdArray=\"+str;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("iframe {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");
List<Cart> cartlist = (List<Cart>)request.getAttribute("cartlist");
  
      out.write("\r\n");
      out.write("    <div style=\"margin:1px auto;width:1366px;background-color:#F6F6F6\">\r\n");
      out.write("    <div id=\"d1\">\r\n");
      out.write("    <div id=\"d11\">送至：北京&or;</div>\r\n");
      out.write("    <div id=\"d12\">\r\n");
      out.write("      <ul class=\"u1\">\r\n");
      out.write("      ");
User user = (User)request.getSession().getAttribute("user"); 
      out.write("\r\n");
      out.write("     \r\n");
      out.write("        <li style=\"width:180px\">欢迎你");
      out.print(user.getUsername() );
      out.write("&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("\r\n");
      out.write("        <li><a style=\"text-decoration:none;\" href=\"showOrder\">我的订单</a></li>\r\n");
      out.write("        <li>我的京东&or;</li>\r\n");
      out.write("        <li>京东会员</li>\r\n");
      out.write("        <li>企业采购</li>\r\n");
      out.write("        <li>手机京东&or;</li>\r\n");
      out.write("        <li>关注京东&or;</li>\r\n");
      out.write("        <li>客户服务&or;</li>\r\n");
      out.write("        <li>网站导航&or;</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d2\">\r\n");
      out.write("    <div id=\"d21\" ></div>\r\n");
      out.write("    <div id=\"d22\">\r\n");
      out.write("      <input class=\"text1\" type=\"text\" id=\"selectbooktext\" placeholder=\"莫言\" style=\"font-weight:bold;color:#C2C2C2\"/>\r\n");
      out.write("      <div class=\"sousuo\">搜索</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d3\">\r\n");
      out.write("    <div id=\"d31\">全部商品");
      out.print(cartlist.size() );
      out.write("</div>\r\n");
      out.write("    <div id=\"d32\">京东大药房</div>\r\n");
      out.write("    <div id=\"d33\">\r\n");
      out.write("      <div class=\"d331\">配送至:</div>\r\n");
      out.write("      <div class=\"d332\">北京朝阳区三环以内&or; </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d4\">\r\n");
      out.write("    <div id=\"d41\" style=\"width:60px;\">\r\n");
      out.write("      <input type=\"checkbox\" class=\"quanxuan\" style=\"margin-top:3px;\" />\r\n");
      out.write("      &nbsp;全选 </div>\r\n");
      out.write("    <div id=\"d41\" style=\"margin-left:75px;\">商品</div>\r\n");
      out.write("    <div id=\"d41\" style=\"margin-left:450px;\">单价</div>\r\n");
      out.write("    <div id=\"d41\" style=\"margin-left:60px;\">数量</div>\r\n");
      out.write("    <div id=\"d41\" style=\"margin-left:90px;\">小计</div>\r\n");
      out.write("    <div id=\"d41\" style=\"margin-left:40px;\">操作</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"d5\">\r\n");
      out.write("    ");
for(int i = 0;i < cartlist.size();i++){ 
      out.write("\r\n");
      out.write("    <div id=\"d51\" data-proid=\"");
      out.print(cartlist.get(i).getProduct().getId() );
      out.write("\" >\r\n");
      out.write("      <div class=\"d511\">\r\n");
      out.write("        <input type=\"checkbox\" class=\"xuanzhong\" style=\"margin-left:10px;\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"d512\"><img style=\"width:80px;height:80px;\"src=\"images/");
      out.print(cartlist.get(i).getProduct().getPicture());
      out.write("\"/></div>\r\n");
      out.write("      <div class=\"d513\">\r\n");
      out.write("        <div>");
      out.print(cartlist.get(i).getProduct().getContent() );
      out.write("</div>\r\n");
      out.write("        <div style=\"clear:both;margin-top:29px;\">\r\n");
      out.write("          <div id=\"qitian\" style=\"float:left\"></div>\r\n");
      out.write("          <div style=\"margin-left:5px;float:left;color:#666\">支持7天无理由退货</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"clear:both;margin-top:53px;\">\r\n");
      out.write("          <div id=\"baozhuang\" style=\"margin-left:0px;float:left\"></div>\r\n");
      out.write("          <div style=\"margin-left:5px;float:left;color:#B2B2B2\">选包装 </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"d514\">颜色：40周年纪念版</div>\r\n");
      out.write("      <div class=\"d515\">¥<a id=\"jiage1\">");
      out.print(cartlist.get(i).getProduct().getPrice() );
      out.write("</a></div>\r\n");
      out.write("      <div class=\"d516\">\r\n");
      out.write("        <div class=\"d5161\">\r\n");
      out.write("          <div class=\"d51611\" >-</div>\r\n");
      out.write("          <div class=\"d51612\">\r\n");
      out.write("            <input type=\"text\" name=\"num\" value=\"");
      out.print(cartlist.get(i).getNum() );
      out.write("\" style=\"width:35px;height:30px;\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"d51613\"  >+</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d5162\">有货 </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"d517\">¥<a class=\"count\">");
      out.print(cartlist.get(i).getCount() );
      out.write("</a></div>\r\n");
      out.write("      <div class=\"d518\">\r\n");
      out.write("        <ul id=\"ul2\" >\r\n");
      out.write("          <li class=\"delete\">删除</li>\r\n");
      out.write("          <li>移到我的关注</li>\r\n");
      out.write("          <li>加到我的关注</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"d6\">\r\n");
      out.write("  <div id=\"d61\">\r\n");
      out.write("    <input type=\"checkbox\" class=\"quanxuan\" style=\"margin-top:3px;\"/>\r\n");
      out.write("    &nbsp;全选 </div>\r\n");
      out.write("  <div id=\"d62\">\r\n");
      out.write("    <ul class=\"ul1\">\r\n");
      out.write("      <li>删除选中的商品</li>\r\n");
      out.write("      <li>移到我的关注</li>\r\n");
      out.write("      <li>清除下柜商品</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d63\">\r\n");
      out.write("    <div style=\"width:36px;float:left;\">已选择</div>\r\n");
      out.write("    <div class=\"selected\" style=\"width:10px;float:left;color:#F00;\">0</div>\r\n");
      out.write("    <div style=\"width:40px;float:left;\">件商品</div>\r\n");
      out.write("    <div name=\"jiantou\">&and;</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d64\">\r\n");
      out.write("    <div  style=\"width:120px;height:18px;\">总价：<span style=\"color:red;font-weight:bold;font-size:15px;\">¥<a class=\"zongjia\">0.00</a></span>\r\n");
      out.write("      <div style=\"float:right;width:12px;height:18px;background-image:url(images/price-tips.png)\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"width:100px;height:25px;\">已节省:-¥0.00</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"d65\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\" class=\"row\">\r\n");
      out.write("   <iframe src=\"footer\" scrolling=\"no\" frameborder=\"0\" \r\n");
      out.write("\t\t\tname=\"footer\" class=\"col-sm-12\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
